### ISSUE TITLE
[UX] Create login button from main website

### ISSUE THREAD

**Issue by adrianchung** [pthieu/asb#3]
The main website probably needs an existing user button to login directly. As is I only get to the login by trying to sign up. 

The default for the sign up page includes my first/last name..  If I just enter my e-mail/password to login I get to the login form, but I expected to get logged in.

**Comment by adrianchung** [comment]
Also, have you considered using something like Auth0 to handle user management so you don't have to do it?

**Comment by pthieu** [comment]
@adrianchung briefly looked into it but I had a react-redux boilerplate ready to go with basic auth capabilities so it was quicker to keep the data and logic in-house

**Comment by pthieu** [comment]
This is has been added in the latest patch.
